# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 0870c0f9dce10e35641ce723b31cfe50e01797f858d76668a2ef7c965cad2dba1a8a4f5c12a550f4613a6f910acd8847075f17ed68cfe21ef16d58b51ffba575
  google_places_key: AIzaSyAvb2OQWipY6XeXhNeHRSgFl5xT-_Z8_rg
  google_dev_secret: TEA9hlSW1BHqC68R0H5RcDmw
  facebook_dev_secret: 3b121d889cc92ad11e9e62eb336ee547
test:
  domain_name: example.com
  secret_key_base: bd7ab85f289d4f4d3f26350f5cf50d703a3e8cf63a8bfee5b078ba67e2d73c6cf0c4d42aa19c4080ca05547f39a77d697853e1fd8c17cac264d663d5135e82cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
